<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(1,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[3]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[4]=array(0,2,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[5]=array(4,2,1,'5Yir5aKF');
$cfg_Cs[6]=array(4,2,1,'5Yqe5YWs56m66Ze0');
$cfg_Cs[7]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[8]=array(7,1,1,'5YWs5Y+45Yqo5oCB');
$cfg_Cs[9]=array(7,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[10]=array(0,1,1,'6KOF5L+u5bi46K+G');
$cfg_Cs[11]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[12]=array(0,1,1,'5Luj6KGo5a6i5oi3');
?>