<figure class="indexCaseItem">
    <p><img  original="[field:picname /]" src="/templets/moban/images/lazy.gif"  width="232" height="170" alt="[field:fulltitle/]" /><a href='[field:arcurl /]' title='[field:fulltitle/]' class='link'><span>
    设计风格：[field:fg/]<br>
        建筑类型：[field:typename /]<br>
        实际面积：[field:mj/]㎡</span></a></p>
     <figcaption><a href="[field:arcurl/]">[field:title/]</a></figcaption>
</figure>