<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:fg itemname="设计风格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fg>

<field:mj itemname="实际面积(㎡)" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:mj>

<field:sj itemname="设计时间" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="2012-07-03至2012-08-20"  maxlength="250" page="">
</field:sj>

<field:xmsj itemname="项目设计" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:xmsj>
