<?php
$z[0]=Array("global","",1346,1373);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1382,1408);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1433,1465);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1488,1514);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1839,1864);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",2142,2167);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",2329,2356);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",2365,2391);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",2555,2717);
$z[8][4]['typeid']="1";
$z[8][4]['type']="son";
$z[8][4]['row']="20";
$z[9]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",2837,2999);
$z[9][4]['typeid']="4";
$z[9][4]['type']="son";
$z[9][4]['row']="20";
$z[10]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",3122,3284);
$z[10][4]['typeid']="7";
$z[10][4]['type']="son";
$z[10][4]['row']="20";
$z[11]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",3414,3577);
$z[11][4]['typeid']="10";
$z[11][4]['type']="son";
$z[11][4]['row']="20";

?>