<?php
$z[0]=Array("global","",1316,1343);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1352,1378);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1403,1435);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1458,1484);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1809,1834);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",2112,2137);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",2299,2326);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",2335,2361);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",2525,2687);
$z[8][4]['typeid']="1";
$z[8][4]['type']="son";
$z[8][4]['row']="20";
$z[9]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",2807,2969);
$z[9][4]['typeid']="4";
$z[9][4]['type']="son";
$z[9][4]['row']="20";
$z[10]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",3092,3254);
$z[10][4]['typeid']="7";
$z[10][4]['type']="son";
$z[10][4]['row']="20";
$z[11]=Array("channel","\r\n<a href=\"[field:typelink/]\"  title=\"[field:typename/]\" class=\"AboutNavMenu6\">[field:typename/]</a>\r\n",3384,3547);
$z[11][4]['typeid']="10";
$z[11][4]['type']="son";
$z[11][4]['row']="20";

?>